version: '3.9'

services:
  osnap-app-sender:
    container_name: osnap-app-sender
    ports:
    - 8000:8000
    command: [ "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "./" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
        BUILDKIT_INLINE_CACHE: 1
    environment:
      DEBUG: 1
      WATCHFILES_FORCE_POLLING: true
    env_file: .env.sender
    volumes:
      - .:/app
    networks: 
      osnap:

  redis-stack-server:
    container_name: redis-stack-server
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    image: redis/redis-stack:latest # redis/redis-stack-server:latest for prod
    command: ["redis-server", "--requirepass", "redis-stack", "--loadmodule", "/opt/redis-stack/lib/redisearch.so", "--loadmodule", "/opt/redis-stack/lib/rejson.so"]
    volumes: 
      - cache:/data
      - redis:/var/lib/redis
    networks:
      osnap:

volumes:
  cache:
    driver: local
  redis:

networks:
  osnap:
    external: true
# #   default:
# #     external:
# #       name: osnap