version: '3.9'

services:
  app-sender:
    container_name: app-sender
    ports:
    - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.sender
      args:
        DOCKER_BUILDKIT: 1
        BUILDKIT_INLINE_CACHE: 1
    environment:
      DEBUG: 1
      WATCHFILES_FORCE_POLLING: true
    env_file: .env.sender
    volumes:
      - .:/app

  sender-redis-stack:
    container_name: sender-redis-stack
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    image: redis/redis-stack:latest # redis/redis-stack-server:latest for prod 
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local

networks:
  default:
    name: 'osnap-network'
    external: true