version: '3.9'

services:
  app-receiver:
    container_name: app-receiver
    ports:
    - 8005:8005
    build:
      context: .
      dockerfile: Dockerfile.receiver
      args:
        DOCKER_BUILDKIT: 1
        BUILDKIT_INLINE_CACHE: 1
    env_file: .env.receiver
    environment:
      DEBUG: 1
      WATCHFILES_FORCE_POLLING: true
    volumes:
      - .:/app
  receiver-redis-stack:
    container_name: receiver-redis-stack 
    restart: always
    ports:
      - 6375:6379
      - 8006:8001
    image: redis/redis-stack:latest # redis/redis-stack-server:latest for prod
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  
networks:
  default:
    name: 'osnap-network'
    external: true